services:
  post-microservice:
    build:
      context: ./post-microservice
      dockerfile: Dockerfile
    ports:
      - 3005:3005

  user-microservice:
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    ports:
      - 3006:3006

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 3007:3007
    depends_on:
      - post-microservice
      - user-microservice